server.port=8080
spring.application.name=gestion-tareas
# DevTools: deshabilitar cache de Thymeleaf en desarrollo
spring.thymeleaf.cache=false
logging.level.com.universidad=DEBUG
# Fechas en formato ISO (yyyy-MM-dd), el mismo que usa input type="date"
spring.mvc.format.date=iso
